# Generated by Django 3.2.6 on 2021-08-18 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название валюты (rus)')),
                ('eng_name', models.CharField(max_length=255, verbose_name='Название валюты (eng)')),
                ('nominal', models.PositiveSmallIntegerField(verbose_name='Номинал единицы')),
                ('parent_code', models.CharField(max_length=255, verbose_name='Parent code')),
                ('iso_num', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Числовой ISO код')),
                ('iso_char', models.CharField(blank=True, max_length=255, null=True, verbose_name='Символьный ISO код')),
            ],
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(verbose_name='Котировка')),
                ('date', models.DateField(verbose_name='Дата')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='api.currency', verbose_name='валюта')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rates',
            constraint=models.UniqueConstraint(fields=('currency', 'rate', 'date'), name='Котировка валюты на день'),
        ),
    ]

